# Generated by Django 3.0.9 on 2020-08-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASBLYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Date de début')),
                ('stop', models.DateField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': "Année d'ASBL",
            },
        ),
    ]
