# Generated by Django 3.0.9 on 2020-08-07 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incubator', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, validators=[users.models.insensitive_unique_username], verbose_name="nom d'utilisateur")),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=127)),
                ('last_name', models.CharField(blank=True, max_length=127)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ardoise')),
                ('has_key', models.BooleanField(default=False, verbose_name='possède une clé')),
                ('hide_pamela', models.BooleanField(default=False, verbose_name='caché sur pamela')),
                ('newsletter', models.BooleanField(default=True, verbose_name='abonné à la newsletter')),
                ('is_active', models.BooleanField(default=True, verbose_name='Utilisateur actif')),
                ('description', models.TextField(default='', max_length=255, verbose_name='Description')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'ordering': ['username'],
                'permissions': (('change_balance', 'Peut modifier son ardoise'),),
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asbl_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incubator.ASBLYear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
