# Generated by Django 3.2.7 on 2021-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200917_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
