# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170419_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[users.models.insensitive_unique_username], verbose_name="nom d'utilisateur"),
        ),
    ]
