# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171009_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='', max_length=255, verbose_name='Description'),
        ),
    ]
