# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_misctransaction_producttransaction_topuptransaction_transfertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='misctransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
