# Generated by Django 3.0.9 on 2020-09-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='picture',
            new_name='receipt',
        ),
    ]
