# Generated by Django 3.0.9 on 2020-09-04 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0005_auto_20200904_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('method', models.CharField(choices=[('a', 'Card'), ('b', 'Cash')], max_length=1)),
                ('way', models.CharField(choices=[('a', 'out'), ('b', 'in')], default='a', max_length=1)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='souches')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.FundZone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
