# Generated by Django 3.0.9 on 2020-09-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200904_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='method',
        ),
        migrations.AddField(
            model_name='fundzone',
            name='method',
            field=models.CharField(choices=[('a', 'Card'), ('b', 'Cash')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
