# Generated by Django 3.0.9 on 2020-09-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200905_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='way',
            field=models.CharField(choices=[('a', 'dépense'), ('b', 'réception')], default='a', max_length=1),
        ),
    ]
