# Generated by Django 3.0.9 on 2020-09-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20200918_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='way',
            field=models.CharField(choices=[('a', 'Dépense'), ('b', 'Réception')], default='a', max_length=1),
        ),
    ]
