# Generated by Django 3.0.9 on 2020-09-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20200928_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
