# Generated by Django 3.0.9 on 2020-08-07 00:42

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nom')),
                ('place', models.CharField(blank=True, max_length=300, verbose_name='Lieu')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de début')),
                ('stop', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin')),
                ('status', models.CharField(choices=[('r', 'Prêt'), ('i', 'En incubation')], max_length=1, verbose_name='Etat')),
                ('description', models.TextField(blank=True)),
                ('picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 500], upload_to='event_pictures')),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ('start', 'stop'),
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OJ', models.TextField(blank=True, verbose_name='Ordre du jour')),
                ('PV', models.TextField(blank=True)),
                ('pad', models.URLField(blank=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Réunion',
                'permissions': (('run_meeting', 'Peut mener des réunions'),),
            },
        ),
    ]
