# Generated by Django 3.0.9 on 2020-09-17 22:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200807_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[500, 500], upload_to='event_pictures'),
        ),
    ]
