# Generated by Django 3.2.1 on 2021-05-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200918_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_talk',
            field=models.BooleanField(default=False),
        ),
    ]
