# Generated by Django 3.0.14 on 2021-04-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_conference_talks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talks',
            new_name='Talk',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='conferenc',
            new_name='conference',
        ),
    ]
