# Generated by Django 3.2.1 on 2021-05-04 19:20

from django.conf import settings
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_event_is_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interesting_events', to=settings.AUTH_USER_MODEL, verbose_name='Personnes intéressées'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_talk',
            field=models.BooleanField(default=False, verbose_name='Cet événement est une conférence'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, size=[500, 500], upload_to='event_pictures', verbose_name='Image'),
        ),
    ]
