# Generated by Django 3.0.9 on 2020-09-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20200807_0242'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom')),
                ('creator', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modifier', models.CharField(default='', max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('commit', models.TextField(blank=True, verbose_name='commit')),
                ('category', models.CharField(choices=[('p', 'Project'), ('f', 'Food'), ('m', 'Miscellaneous'), ('o', 'Objects'), ('h', 'Hackerspace')], max_length=1)),
            ],
            options={
                'verbose_name': 'Article',
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom')),
                ('creator', models.CharField(max_length=50)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('last_modifier', models.CharField(default='', max_length=50)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('commit', models.TextField(blank=True, verbose_name='commit')),
                ('category', models.CharField(choices=[('p', 'Project'), ('f', 'Food'), ('m', 'Miscellaneous'), ('o', 'Objects'), ('h', 'Hackerspace')], max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Article',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectLinkedArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.Article')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            bases=('wiki.article',),
        ),
    ]
