# Generated by Django 3.0.9 on 2020-09-04 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarticle',
            name='last_modifier',
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='writted_article', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_modifier',
        ),
        migrations.AddField(
            model_name='article',
            name='last_modifier',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
