# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-29 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nbr_revision',
            field=models.IntegerField(default=0),
        ),
    ]
