# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_article_nbr_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Article', max_length=200),
        ),
    ]
