# Generated by Django 3.0.9 on 2020-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20200904_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalarticle',
            name='last_modifier',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_modifier',
        ),
        migrations.AddField(
            model_name='article',
            name='last_modifier',
            field=models.CharField(default='', max_length=50),
        ),
    ]
