# Generated by Django 3.0.9 on 2020-09-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20200904_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('p', 'Project'), ('f', 'Nourriture'), ('m', 'Divers'), ('o', 'Objects'), ('h', 'Hackerspace')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='category',
            field=models.CharField(choices=[('p', 'Project'), ('f', 'Nourriture'), ('m', 'Divers'), ('o', 'Objects'), ('h', 'Hackerspace')], max_length=1),
        ),
    ]
