# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20190206_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
    ]
