# Generated by Django 3.0.9 on 2020-10-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20200915_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Caché'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Caché'),
        ),
    ]
