# Generated by Django 3.2.14 on 2022-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20201012_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalarticle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Article', 'verbose_name_plural': 'historical Articles'},
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
