# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_historicalarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('p', 'project'), ('f', 'food'), ('m', 'miscellaneous'), ('o', 'objects')], default='p', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='category',
            field=models.CharField(choices=[('p', 'project'), ('f', 'food'), ('m', 'miscellaneous'), ('o', 'objects')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
