# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170922_1832'),
        ('wiki', '0007_auto_20190219_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLinkedArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.Article')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            bases=('wiki.article',),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('p', 'Project'), ('f', 'Food'), ('m', 'Miscellaneous'), ('o', 'Objects'), ('h', 'Hackerspace')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='category',
            field=models.CharField(choices=[('p', 'Project'), ('f', 'Food'), ('m', 'Miscellaneous'), ('o', 'Objects'), ('h', 'Hackerspace')], max_length=1),
        ),
    ]
