# Generated by Django 3.2.18 on 2023-03-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20220707_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Privé'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Privé'),
        ),
    ]
