# Generated by Django 3.2.18 on 2023-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20230327_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Seulement visible avec un lien direct', verbose_name='Caché'),
        ),
        migrations.AlterField(
            model_name='article',
            name='private',
            field=models.BooleanField(default=False, help_text='Seulement visible par les membres du staff', verbose_name='Privé'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Seulement visible avec un lien direct', verbose_name='Caché'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='private',
            field=models.BooleanField(default=False, help_text='Seulement visible par les membres du staff', verbose_name='Privé'),
        ),
    ]
