# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20190314_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commit',
            field=models.TextField(blank=True, verbose_name='commit'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='commit',
            field=models.TextField(blank=True, verbose_name='commit'),
        ),
    ]
