# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-03 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20190503_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, default=1, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='nbr_revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='nbr_revision',
            field=models.IntegerField(default=0),
        ),
    ]
