# Generated by Django 3.0.9 on 2020-08-07 00:42

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('p', 'proposition'), ('i', 'in progress'), ('f', 'finished'), ('a', 'ants are gone')], max_length=1, verbose_name='État')),
                ('progress', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Progression')),
                ('picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 500], upload_to='project_pictures')),
                ('short_description', models.CharField(max_length=1000, verbose_name='Description courte')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Projet',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nom')),
                ('proposed_on', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('completed_on', models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation')),
            ],
        ),
    ]
