# Generated by Django 3.0.9 on 2020-09-17 22:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200918_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, size=[500, 500], upload_to='project_pictures'),
        ),
    ]
