# Generated by Django 3.2.1 on 2021-06-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20200918_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('down_vote_user', models.ManyToManyField(related_name='down_vote', to=settings.AUTH_USER_MODEL, verbose_name='Dislike')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='Projet')),
                ('up_vote_user', models.ManyToManyField(related_name='up_vote', to=settings.AUTH_USER_MODEL, verbose_name='Like')),
            ],
        ),
    ]
