# Generated by Django 3.2.7 on 2021-10-04 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='down_vote_user',
            field=models.ManyToManyField(blank=True, related_name='down_vote', to=settings.AUTH_USER_MODEL, verbose_name='Dislike'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='up_vote_user',
            field=models.ManyToManyField(blank=True, related_name='up_vote', to=settings.AUTH_USER_MODEL, verbose_name='Like'),
        ),
    ]
