# Generated by Django 3.2.17 on 2023-02-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211004_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('p', 'proposition'), ('i', 'in progress'), ('f', 'finished'), ('a', 'ants are gone'), ('d', 'blocked to 131')], max_length=1, verbose_name='État'),
        ),
    ]
