# Generated by Django 4.2.29 on 2026-03-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='projects.project', verbose_name='Dépendences'),
        ),
    ]
