sudo: false

language: python

python:
  - "3.8"

cache: pip

install:
  - "pip install -U pip setuptools"
  - "pip install -r requirements.txt"


script:
  - flake8 --ignore=E501,F401,E402,F811,E731,F403 .
  - ./manage.py check
  - FAKE_REDIS=1 DEBUG=1 py.test


notifications:
  email:
    on_success: change
    on_failure: change
