sudo: false

language: python

python:
  - "3.6"

cache: pip

install:
  - "pip install -U pip setuptools"
  - "pip install -r requirements.txt"


script:
  - ./manage.py check
  - py.test


notifications:
  email:
    on_success: change
    on_failure: change
