# Generated by Django 3.0.9 on 2020-08-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=511, verbose_name='Sujet')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('sent', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
