# Generated by Django 3.0.9 on 2020-08-07 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approved_emails', to=settings.AUTH_USER_MODEL, verbose_name='Approbateurs'),
        ),
    ]
