# Generated by Django 3.0.9 on 2020-09-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('target', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Redirection',
                'verbose_name_plural': 'Redirections',
            },
        ),
    ]
