# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import space.models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20160102_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacestatus',
            name='time',
            field=models.DateTimeField(default=space.models._auto_now),
        ),
    ]
