# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-06 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_auto_20160929_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceStatusPrediction',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('proba_open', models.FloatField()),
            ],
            options={
                'verbose_name_plural': "Prévisions d'état d'ouverture du Hackerspace",
                'verbose_name': "Prévision d'état d'ouverture du Hackerspace",
            },
        ),
    ]
