name: CI to replace (?) travis or at least to be used until we fix travis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run: |
          pip install -U pip setuptools
          pip install -r requirements.txt

      - name: Make the tests
        run: |
          ./manage.py check
          FAKE_REDIS=1 DEBUG=1 py.test
