name: CI to replace (?) travis or at least to be used until we fix travis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: python-alpine

    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          - pip install -U pip setuptools
          - pip install -r requirements.txt
          - ./manage.py check
          - FAKE_REDIS=1 DEBUG=1 py.test
