name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install Python dependencies
        run: uv sync --all-groups

      - name: Lint python code
        run: uv run flake8 --ignore=E501,F401,E402,F811,E731,F403,E721 --exclude=.git,*migrations*,ve,.venv .

      - name: Run django checks
        run: uv run ./manage.py check

      - name: Check migrations
        run: uv run ./manage.py makemigrations --dry-run --check

      - name: Run tests
        run: FAKE_REDIS=1 DEBUG=1 uv run py.test
