# Generated by Django 3.2.7 on 2021-10-18 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0003_auto_20200929_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'permissions': (('approve_badge', 'Peut approuver une proposition de badge'),)},
        ),
        migrations.AddField(
            model_name='badge',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='initiateur'),
        ),
    ]
