# Generated by Django 3.2.1 on 2021-10-27 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0004_auto_20211018_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgewear',
            name='action_counter',
        ),
        migrations.AddField(
            model_name='badge',
            name='has_level',
            field=models.BooleanField(default=True, verbose_name='Possède des niveaux ?'),
        ),
        migrations.AlterField(
            model_name='badgewear',
            name='attributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed', to=settings.AUTH_USER_MODEL, verbose_name='Attributeur'),
        ),
        migrations.AlterField(
            model_name='badgewear',
            name='level',
            field=models.CharField(blank=True, choices=[('RAC', 'Raclure de bidet'), ('INI', 'Initié'), ('DIS', 'Disciple'), ('MAI', 'Maître')], default='INI', max_length=3, null=True),
        ),
    ]
